export function qs(selector) {
  return document.querySelector(selector);
}

export const ui = {
  screens: [...document.querySelectorAll("[data-screen]")],
  startGame: qs("#start-game"),
  aboutGame: qs("#about-game"),
  shareGame: qs("#share-game"),
  shareFeedback: qs("#share-feedback"),
  backToStart: qs("#back-to-start"),
  backToVariants: qs("#back-to-variants"),
  backToModes: qs("#back-to-modes"),
  board: qs("#board"),
  score: qs("#score"),
  best: qs("#best"),
  moves: qs("#moves"),
  status: qs("#status"),
  tutorialCoach: qs("#tutorial-coach"),
  tutorialKicker: qs("#tutorial-kicker"),
  tutorialTitle: qs("#tutorial-title"),
  tutorialBody: qs("#tutorial-body"),
  tutorialInstruction: qs("#tutorial-instruction"),
  modeLabel: qs("#mode-label"),
  modeTimer: qs("#mode-timer"),
  restart: qs("#restart"),
  changeLevel: qs("#change-level"),
  changeMode: qs("#change-mode"),
  menuToggle: qs("#menu-toggle"),
  menuPanel: qs("#menu-panel"),
  variantButtons: [...document.querySelectorAll("[data-variant]")],
  modeButtons: [...document.querySelectorAll("[data-mode]")],
  levelButtons: [...document.querySelectorAll("[data-size]")],
  dialog: qs("#game-over"),
  finalScore: qs("#final-score"),
  modalKicker: qs("#modal-kicker"),
  modalTitle: qs("#modal-title"),
  modalMessage: qs("#modal-message"),
  modalScore: qs("#modal-score"),
  modalBest: qs("#modal-best"),
  modalMoves: qs("#modal-moves"),
  modalMode: qs("#modal-mode"),
  modalBoard: qs("#modal-board"),
  modalFruits: qs("#modal-fruits"),
  playAgain: qs("#play-again"),
  aboutDialog: qs("#about-dialog"),
  closeAbout: qs("#close-about")
};
